% -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
%    ][
%    ][                                                 IC GUI Main
%    ][
%    ][    This function will create a GUI from Internal Combustion (IC)   
%    ][    original program for test the program.
%    ][
%    ][    Original created by : Tonkid Chantrasmi
%    ][    Renew created by : Wassanun Sangjun
%    ][    Date : 11/04/2016
%    ][    
% -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-

function ic_gui_main()

    clc;
    clear all;
    close all;
    
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    %                                   GUI properties initialization 
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    font_type = 'Calibri';
    font_size_1 = 10;
    font_size_2 = 11;
    font_size_3 = 12;
    font_size_4 = 13;
    font_color_1 = [0 0 0]; % Black Color
    font_color_2 = [1 1 1]; % White Color
    bg_color_1 = [0 0 0]; % Black Color
    bg_color_2 = [1 1 1]; % White Color
    
    no_geo_list = {'1','2','3','4','5'}; % Number of Geometries
    no_prop_list = {'1','2','3'}; % Number of Propellants
    
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    %                                   Create GUI and set background 
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-

    % Create GUI figure. (set name, size and position)
    main_ic_gui = figure('name','Internal Combustion (IC) for Internal Ballistic','numbertitle','off',...
              'position',[0 0 1000 600],'resize','off','color','white');
    movegui(main_ic_gui,'center');
    
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    %                                   Create all components of GUI 
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    
    % GUI panel.
    % ---------------------------------------------------------------------------------
    
    % Column 1
    % ---------------------
    nozzle_uipanel = uipanel('title','Nozzle','fontsize',font_size_2,'fontname',font_type,...
                                        'foregroundcolor','black','backgroundcolor','none','position',[0.025 0.8 0.3 0.125],...
                                        'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                        'parent',main_ic_gui);
    ignitor_uipanel = uipanel('title','Ignitor','fontsize',font_size_2,'fontname',font_type,...
                                        'foregroundcolor','black','backgroundcolor','none','position',[0.025 0.61 0.3 0.175],...
                                        'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                        'parent',main_ic_gui);
    numerical_parameters_uipanel = uipanel('title','Numerical Parameters','fontsize',font_size_2,...
                                                               'fontname',font_type,'backgroundcolor','none','position',[0.025 0.2175 0.3 0.375],...
                                                               'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                                               'parent',main_ic_gui);
                                                           
    % Column 2
    % ---------------------
    propellants_uipanel = uipanel('title','Propellants','fontsize',font_size_2,'fontname',font_type,...
                                              'foregroundcolor','black','backgroundcolor','none','position',[0.355 0.0385 0.2925 0.75],...
                                              'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                              'parent',main_ic_gui);
    sub_prop1_uipanel = uipanel('title','Propellants #1 (innermost)','fontsize',font_size_2,'fontname',font_type,...
                                              'foregroundcolor','black','backgroundcolor','none','position',[0.075 0.75 0.85 0.225],...
                                              'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                              'parent',propellants_uipanel);                                      
    sub_prop2_uipanel = uipanel('title','Propellants #2','fontsize',font_size_2,'fontname',font_type,...
                                              'foregroundcolor','black','backgroundcolor','none','position',[0.075 0.4 0.85 0.225],...
                                              'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                              'parent',propellants_uipanel);
    sub_prop3_uipanel = uipanel('title','Propellants #3','fontsize',font_size_2,'fontname',font_type,...
                                              'foregroundcolor','black','backgroundcolor','none','position',[0.075 0.05 0.85 0.225],...
                                              'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                              'parent',propellants_uipanel);                                      
                                          
    % Column 3
    % ---------------------
    geo1_uipanel = uipanel('title','Geometry #1 (near ignitor)','fontsize',font_size_2,'fontname',font_type,...
                                     'foregroundcolor','black','backgroundcolor','none','position',[0.675 0.775 0.3 0.15],...
                                     'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                     'parent',main_ic_gui);
    geo2_uipanel = uipanel('title','Geometry #2','fontsize',font_size_2,'fontname',font_type,...
                                     'foregroundcolor','black','backgroundcolor','none','position',[0.675 0.6 0.3 0.15],...
                                     'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                     'parent',main_ic_gui);                               
    geo3_uipanel = uipanel('title','Geometry #3','fontsize',font_size_2,'fontname',font_type,...
                                     'foregroundcolor','black','backgroundcolor','none','position',[0.675 0.425 0.3 0.15],...
                                     'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                     'parent',main_ic_gui);                                
    geo4_uipanel = uipanel('title','Geometry #4','fontsize',font_size_2,'fontname',font_type,...
                                     'foregroundcolor','black','backgroundcolor','none','position',[0.675 0.250 0.3 0.15],...
                                     'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                     'parent',main_ic_gui);                                
    geo5_uipanel = uipanel('title','Geometry #5','fontsize',font_size_2,'fontname',font_type,...
                                     'foregroundcolor','black','backgroundcolor','none','position',[0.675 0.075 0.3 0.15],...
                                     'bordertype','line','highlightcolor',bg_color_1,'borderwidth',3,...
                                     'parent',main_ic_gui);                               
                                    
    % Tag or text description.
    % ---------------------------------------------------------------------------------
    
    % Column 1
    % ---------------------
    tag_1 = uicontrol('style','text','string','Instruction : This program will compute an internal combustion (IC) of internal ballistic (IB).',...
                             'position',[30 590 615 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_4,'backgroundcolor',bg_color_2);
    tag_2 = uicontrol('style','text','string','Throat diameter :',...
                              'position',[15 20 120 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',nozzle_uipanel);
    tag_3 = uicontrol('style','text','string','mm',...
                              'position',[240 20 30 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',nozzle_uipanel);
    tag_4 = uicontrol('style','text','string','Ignition mass :',...
                              'position',[15 55 100 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',ignitor_uipanel);
    tag_5 = uicontrol('style','text','string','kg',...
                              'position',[240 55 20 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',ignitor_uipanel);
    tag_6 = uicontrol('style','text','string','Ignition time :',...
                              'position',[15 20 100 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',ignitor_uipanel);                      
    tag_7 = uicontrol('style','text','string','s',...
                              'position',[240 20 10 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',ignitor_uipanel);                      
    tag_8 = uicontrol('style','text','string','Max element length :',...
                              'position',[15 175 145 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);
    tag_9 = uicontrol('style','text','string','m',...
                              'position',[240 175 15 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);
    tag_10 = uicontrol('style','text','string','Time step size :',...
                               'position',[15 140 105 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                               'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);                      
    tag_11 = uicontrol('style','text','string','s',...
                              'position',[240 140 10 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);                      
    tag_12 = uicontrol('style','text','string','Max no. time steps :',...
                               'position',[15 105 135 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                               'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);                      
    tag_13 = uicontrol('style','text','string','steps',...
                              'position',[240 105 40 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);
    tag_14 = uicontrol('style','text','string','Initial P guess :',...
                               'position',[15 70 105 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                               'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);
    tag_15 = uicontrol('style','text','string','PSI',...
                              'position',[240 70 25 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                              'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);                       
    tag_16 = uicontrol('style','text','string','Rel. tol. for P :',...
                               'position',[15 35 95 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                               'foregroundcolor',font_color_1,'backgroundcolor','default','parent',numerical_parameters_uipanel);
    tag_progress = uicontrol('style','text','string','Progress : 0%',...
                                         'position',[150 99 115 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                                         'foregroundcolor',font_color_1,'backgroundcolor','default','parent',main_ic_gui);                       
    
    % Column 2
    % ---------------------                       
    tag_17 = uicontrol('style','text','string','Number of Geometries :',...
                               'position',[370 548 160 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',main_ic_gui);
    tag_18 = uicontrol('style','text','string','Number of Propellants :',...
                               'position',[370 513 160 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',main_ic_gui);
    tag_19 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 15 200 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',sub_prop1_uipanel);
    tag_20 = uicontrol('style','text','string','offset :',...
                               'position',[55 300 50 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',propellants_uipanel);                       
    tag_21 = uicontrol('style','text','string','mm',...
                               'position',[190 300 30 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',propellants_uipanel);                       
    tag_22 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 15 200 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',sub_prop2_uipanel);
    tag_23 = uicontrol('style','text','string','offset :',...
                               'position',[55 140 50 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',propellants_uipanel);                       
    tag_24 = uicontrol('style','text','string','mm',...
                               'position',[190 140 30 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',propellants_uipanel);                       
    tag_25 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 15 200 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',sub_prop3_uipanel);                       
                           
    % Column 3
    % ---------------------
    tag_26 = uicontrol('style','text','string','Length :',...
                               'position',[95 43 100 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo1_uipanel);
    tag_27 = uicontrol('style','text','string','m',...
                               'position',[245 43 20 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo1_uipanel);
    tag_28 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 10 250 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo1_uipanel);
    tag_29 = uicontrol('style','text','string','Length :',...
                               'position',[95 43 100 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo2_uipanel);
    tag_30 = uicontrol('style','text','string','m',...
                               'position',[245 43 20 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo2_uipanel);
    tag_31 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 10 250 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo2_uipanel);                       
    tag_32 = uicontrol('style','text','string','Length :',...
                               'position',[95 43 100 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo3_uipanel);
    tag_33 = uicontrol('style','text','string','m',...
                               'position',[245 43 20 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo3_uipanel);
    tag_34 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 10 250 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo3_uipanel);                       
    tag_35 = uicontrol('style','text','string','Length :',...
                               'position',[95 43 100 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo4_uipanel);
    tag_36 = uicontrol('style','text','string','m',...
                               'position',[245 43 20 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo4_uipanel);
    tag_37 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 10 250 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo4_uipanel);                       
    tag_38 = uicontrol('style','text','string','Length :',...
                               'position',[95 43 100 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo5_uipanel);
    tag_39 = uicontrol('style','text','string','m',...
                               'position',[245 43 20 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo5_uipanel);
    tag_40 = uicontrol('style','text','string',sprintf('File : %s','-'),...
                               'position',[20 10 250 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',geo5_uipanel);                                                                       
    tag_41 = uicontrol('style','text','string',sprintf('Total Length = %3.3f m',0.0),...
                               'position',[700 20 250 20],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_3,...
                               'backgroundcolor',bg_color_2,'parent',main_ic_gui);                                                    
                                                  
    % Button.
    % ---------------------------------------------------------------------------------

    % Column 1
    % ---------------------
    compute = uicontrol('style','pushbutton','string','Compute','backgroundcolor','default',...
                                  'position',[30 95 100 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                  'parent',main_ic_gui);
    plot_graph = uicontrol('style','pushbutton','string','Plot Graph','backgroundcolor','default',...
                                  'position',[30 50 125 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                  'parent',main_ic_gui);                          
    export_file = uicontrol('style','pushbutton','string','Export File','backgroundcolor','default',...
                                  'position',[180 50 125 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                  'parent',main_ic_gui);
                              
    % Column 2
    % ---------------------
    select_prop1 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                  'position',[20 45 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                  'parent',sub_prop1_uipanel);
    view_1 = uicontrol('style','pushbutton','string','View/Edit','backgroundcolor','default',...
                               'position',[120 45 100 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                               'parent',sub_prop1_uipanel);                          
    select_prop2 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                  'position',[20 45 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                  'parent',sub_prop2_uipanel);
    view_2 = uicontrol('style','pushbutton','string','View/Edit','backgroundcolor','default',...
                               'position',[120 45 100 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                               'parent',sub_prop2_uipanel);
    select_prop3 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                  'position',[20 45 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                  'parent',sub_prop3_uipanel);
    view_3 = uicontrol('style','pushbutton','string','View/Edit','backgroundcolor','default',...
                               'position',[120 45 100 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                               'parent',sub_prop3_uipanel);                       
   
    % Column 3
    % ---------------------
    select_geo1 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                       'position',[20 40 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                       'parent',geo1_uipanel);                       
    select_geo2 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                       'position',[20 40 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                       'parent',geo2_uipanel);                       
    select_geo3 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                       'position',[20 40 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                       'parent',geo3_uipanel);                       
    select_geo4 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                       'position',[20 40 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                       'parent',geo4_uipanel);                       
    select_geo5 = uicontrol('style','pushbutton','string','Select','backgroundcolor','default',...
                                       'position',[20 40 80 30],'horizontalalignment','center','fontname',font_type,'fontsize',font_size_2,...
                                       'parent',geo5_uipanel);                       
                              
    % Textbox.
    % ---------------------------------------------------------------------------------
    
    % Column 1
    % ---------------------
    throat_diameter_box = uicontrol('style','edit','backgroundcolor','white','position',[165 17 60 30],'horizontalalignment','center',...
                                                     'fontname',font_type,'fontsize',font_size_1,'parent',nozzle_uipanel);
    ign_mass_box = uicontrol('style','edit','backgroundcolor','white','position',[165 53 60 30],'horizontalalignment','center',...
                                          'fontname',font_type,'fontsize',font_size_1,'parent',ignitor_uipanel);
    ign_time_box = uicontrol('style','edit','backgroundcolor','white','position',[165 18 60 30],'horizontalalignment','center',...
                                         'fontname',font_type,'fontsize',font_size_1,'parent',ignitor_uipanel);
    max_element_box = uicontrol('style','edit','backgroundcolor','white','position',[165 173 60 30],'horizontalalignment','center',...
                                                'fontname',font_type,'fontsize',font_size_1,'parent',numerical_parameters_uipanel);                                 
    time_step_box = uicontrol('style','edit','backgroundcolor','white','position',[165 138 60 30],'horizontalalignment','center',...
                                           'fontname',font_type,'fontsize',font_size_1,'parent',numerical_parameters_uipanel);                                 
    max_tstep_box = uicontrol('style','edit','backgroundcolor','white','position',[165 103 60 30],'horizontalalignment','center',...
                                            'fontname',font_type,'fontsize',font_size_1,'parent',numerical_parameters_uipanel);                                 
    initial_p_box = uicontrol('style','edit','backgroundcolor','white','position',[165 68 60 30],'horizontalalignment','center',...
                                        'fontname',font_type,'fontsize',font_size_1,'parent',numerical_parameters_uipanel);
    rel_tol_box = uicontrol('style','edit','backgroundcolor','white','position',[165 33 60 30],'horizontalalignment','center',...
                                       'fontname',font_type,'fontsize',font_size_1,'parent',numerical_parameters_uipanel);                                    
                                        
    % Column 2
    % ---------------------
    offset1_box = uicontrol('style','edit','backgroundcolor','white','position',[120 298 60 30],'horizontalalignment','center',...
                                        'fontname',font_type,'fontsize',font_size_1,'parent',propellants_uipanel);
    offset2_box = uicontrol('style','edit','backgroundcolor','white','position',[120 138 60 30],'horizontalalignment','center',...
                                        'fontname',font_type,'fontsize',font_size_1,'parent',propellants_uipanel);                                
    
    % Column 3
    % ---------------------
    geo1_box = uicontrol('style','edit','backgroundcolor','white','position',[180 40 60 30],'horizontalalignment','center',...
                                    'fontname',font_type,'fontsize',font_size_1,'parent',geo1_uipanel);
    geo2_box = uicontrol('style','edit','backgroundcolor','white','position',[180 40 60 30],'horizontalalignment','center',...
                                    'fontname',font_type,'fontsize',font_size_1,'parent',geo2_uipanel);
    geo3_box = uicontrol('style','edit','backgroundcolor','white','position',[180 40 60 30],'horizontalalignment','center',...
                                    'fontname',font_type,'fontsize',font_size_1,'parent',geo3_uipanel);                            
    geo4_box = uicontrol('style','edit','backgroundcolor','white','position',[180 40 60 30],'horizontalalignment','center',...
                                    'fontname',font_type,'fontsize',font_size_1,'parent',geo4_uipanel);                            
    geo5_box = uicontrol('style','edit','backgroundcolor','white','position',[180 40 60 30],'horizontalalignment','center',...
                                    'fontname',font_type,'fontsize',font_size_1,'parent',geo5_uipanel);                                                                                     
    
    % Popup list view.
    % ---------------------------------------------------------------------------------
    
    % Column 2
    % ---------------------
    no_geometries_list = uicontrol('style','popupmenu','foregroundcolor','black','backgroundcolor','white',...
                                                 'position',[540 553 55 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                                                 'parent',main_ic_gui);
    set(no_geometries_list,'string',no_geo_list);
    no_propellants_list = uicontrol('style','popupmenu','foregroundcolor','black','backgroundcolor','white',...
                                                 'position',[540 518 55 20],'horizontalalignment','left','fontname',font_type,'fontsize',font_size_3,...
                                                 'parent',main_ic_gui);
    set(no_propellants_list,'string',no_prop_list);
    
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    %                                  GUI component initialization  
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    
    % Call function to initialize variable.
    [d_throat,mass_ig,time_ig,dx,dt,max_nt,p_initial_guess,tol,offset1,offset2,...
     length1,length2,length3,length4,length5] = ic_gui_default();
    
    % Set value after call function.
    set(throat_diameter_box,'string',d_throat);
    set(ign_mass_box,'string',mass_ig);
    set(ign_time_box,'string',time_ig);
    set(max_element_box,'string',dx);
    set(time_step_box,'string',dt);
    set(max_tstep_box,'string',max_nt);
    set(initial_p_box,'string',p_initial_guess);
    set(rel_tol_box,'string',sprintf('%.1e',tol));
    set(offset1_box,'string',offset1);
    set(offset2_box,'string',offset2);
    set(geo1_box,'string',length1);
    set(geo2_box,'string',length2);
    set(geo3_box,'string',length3);
    set(geo4_box,'string',length4);
    set(geo5_box,'string',length5);
    
    % Set status of object in GUI (default).
    % Column 1
    % ---------------------
    set(compute,'enable','off');
    set(plot_graph,'enable','off');
    set(export_file,'enable','off');
    
    % Column 2
    % ---------------------
    set(offset1_box,'enable','off');
    set(offset2_box,'enable','off');
    set(select_prop2,'enable','off');
    set(view_2,'enable','off');
    set(select_prop3,'enable','off');
    set(view_3,'enable','off');
    
    % Column 3
    % ---------------------
    set(select_geo2,'enable','off');
    set(geo2_box,'enable','off');
    set(select_geo3,'enable','off');
    set(geo3_box,'enable','off');
    set(select_geo4,'enable','off');
    set(geo4_box,'enable','off');
    set(select_geo5,'enable','off');
    set(geo5_box,'enable','off');
    
    % Calculation total length.
    num_geo_box = get(no_geometries_list,'value');
    cal_total_length(num_geo_box)
    
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    %                                     GUI callback function  
    % -o][=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=][o-
    
    % ---------------------------------------------------------------------------------
    %                           Function : Calculation Total Length 
    % ---------------------------------------------------------------------------------   
    function cal_total_length(hobject,eventdata,show_dxf)
    
end